### ISSUE TITLE
Please release on PyPi

### ISSUE THREAD

**Issue by thedrow** [kezabelle/django-haystackbrowser#6]

**Comment by mrben** [comment]
Love this app, thanks! Have been using this is Django 1.6 just fine for the last month.

Would like to :+1: a PyPi release.

Thanks again.

**Comment by mverleg** [comment]
+1 here too (django 1.8)

**Comment by kezabelle** [comment]
I can't imagine anyone but @mverleg (as the most recent requester) in this thread still cares, but I've finally got around to it: https://pypi.python.org/pypi/django-haystackbrowser/0.6.1 ... only 2+ years later!

`0.6.1` is the same as `master` currently stands (8bec2828acd2ce0338e598006cec889b4f9a3645) which itself hasn't changed since 1c77c87159059709c271557a41623fa3b01500b5, and none of the changes since 6fdeb2c4a39cef94c83c086fa9c0f45dd35f8935 (the last external contribution/fix - #12) should have broken anything, hopefully.

As I don't work on this often, and only tend to do so as-necessary on projects which aren't Django LTS, if any of you find yourself using it on Django 1.9+ and encountering any problems, do let me know. 

Thanks for the push, and for having used the package at some point, all of you.

**Comment by mverleg** [comment]
Yaay it works!

**Comment by mrben** [comment]
💯
